databases.admin.datasources.ldap.ldapds.URI=ldap\://tata-black.denodo.com\:389/
databases.admin.datasources.ldap.ldapds.USERNAME=administrator@labs.denodo.loc
databases.admin.datasources.ldap.ldapds.USERPASSWORD=4/xYYg7ue88nYODbo620fEOGzGFYixP7vTYSj8UaDGNfY1RXNEGgzHUiF5xHgeSeALPojNhusedjZaRDZgT7pUkj3b5sUMIEOHEtVD45OSJusEG/YC4z5enLq6JDq+zB
databases.admin.datasources.ldap.ldapds.USERPASSWORD.ENCRYPTED=ENCRYPTED
