databases.admin.datasources.jdbc.ds_mysql.DATABASEURI=jdbc\:mysql\://localhost\:3306/Sys?serverTimezone\=CST
databases.admin.datasources.jdbc.ds_mysql.USERNAME=root
databases.admin.datasources.jdbc.ds_mysql.USERPASSWORD=e6nlfyDFJicOkFb/1bCeYnDfbzLEbofPP87VJ4BEyx3Sidkb24jMTTXNdOSGgQdgcOUkcmeqc0f1NY+Uw2NyhR8aXrD61yDSRBizvmscZme9YovfJcFvp8WPH6g7x1Qn
databases.admin.datasources.jdbc.ds_mysql.USERPASSWORD.ENCRYPTED=ENCRYPTED
